### ISSUE TITLE
Des "Display Error" s'affichent dans les instructions SM.

### ISSUE THREAD

**Issue by kurowasan** [solran/src#2]

**Comment by kurowasan** [comment]
C'est réglé! En fait, dans Langue le Hashmap "TaskNames" était seulement déclaré dans le menu. Comme l'applet ne passe pas pour le menu, ça laissait le texte à "Display Error".

**Comment by solran** [comment]
Ah bon tu as été plus rapide que moi, je pensais voir ca ce soir! Super!

Le 25 juillet 2013 11:36, kurowasan notifications@github.com a écrit :

> C'est réglé! En fait, dans Langue le Hashmap "TaskNames" était seulement
> déclaré dans le menu. Comme l'applet ne passe pas pour le menu, ça laissait
> le texte à "Display Error".
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/solran/src/issues/2#issuecomment-21562555
> .

## 

Maxime Lussier
Doctorant, Université du Québec à Montréal

Laboratoire d'étude de la santé cognitive des ainés- LESCA
Centre de recherche
Institut universitaire de gériatrie de Montréal
4565, chemin Queen-Mary
Montréal QC H3W 1W5
